ros-planning/moveit_grasps

include/moveit_grasps/grasp_generator.h
src/grasp_data.cpp
src/grasp_generator.cpp
src/grasp_planner.cpp

The biggest fix is replacing the commented out call to computeCartesianPathSegmented with three calls to computeCartesianPath

misc fixup to moveit_grasps

---

.clang-format
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_filter.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_planner.h
include/moveit_grasps/state_validity_callback.h
launch/end_effector_setup.launch
launch/rviz.launch
launch/test_bounding_box.launch
launch/test_grasp_generator.launch
src/grasp_candidate.cpp
src/grasp_data.cpp
src/grasp_filter.cpp
src/grasp_generator.cpp
src/grasp_planner.cpp
src/grasp_poses_visualizer.cpp
src/grasp_scorer.cpp

- Remove dead code
- Clang format
- Remove trailing whitespace
- Update email addresses
- Improve comments and TODOs
- Move member variables to bottom of header file
- Fix couts
- Fix deprecated code

Cleanup code

---

CMakeLists.txt
config/moveit_grasps_config.yaml
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_planner.h
src/grasp_candidate.cpp
src/grasp_planner.cpp

fixes some bugs in the cartesian planning, removes redundant parameters from the API and cleans up the planner parameters.

Cartesian planner fixup

---

CMakeLists.txt
README.md
config/moveit_grasps_config.yaml
config_robot/panda_grasp_data.yaml
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_data.h
include/moveit_grasps/grasp_generator.h
launch/test_grasp_generator.launch
package.xml
src/grasp_candidate.cpp
src/grasp_data.cpp
src/grasp_generator.cpp
src/grasp_planner.cpp
src/grasp_poses_visualizer.cpp
src/test/grasp_filter_test.cpp
src/test/grasp_generator_demo.cpp
src/test/mesh_bounding_box_test.cpp

- Run and address roslint
- Run and address catkin lint
- Fix build warnings
- Create initial test

Add testing: roslint, catkin lint, unit test

---

include/moveit_grasps/grasp_data.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_scorer.h
src/grasp_data.cpp
src/grasp_filter.cpp
src/grasp_generator.cpp
src/grasp_planner.cpp
src/grasp_poses_visualizer.cpp
src/grasp_scorer.cpp
test/grasp_data_test.cpp
test/grasp_generator_test.cpp

These changes support suction grippers in addition to standard two finger grippers

Suction gripper

---

README.md

Actually I'm just testing out a new WIP plugin for Github

Document Suction

---

.travis.yml
README.md
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_data.h
include/moveit_grasps/grasp_filter.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_planner.h
include/moveit_grasps/grasp_scorer.h
moveit_grasps.rosinstall
src/demo/grasp_filter_demo.cpp
src/demo/grasp_generator_demo.cpp
src/demo/grasp_pipeline_demo.cpp
src/demo/grasp_poses_visualizer_demo.cpp
src/grasp_candidate.cpp
src/grasp_filter.cpp
src/grasp_generator.cpp
src/grasp_planner.cpp
src/grasp_scorer.cpp
test/grasp_data_test.cpp
test/grasp_generator_test.cpp

Applies necessary changes to new melodic branch.
* update references melodic->kinetic
* refactor Affine3d -> Isometry3d

Fix (initial) melodic-devel branch

---

config_robot/panda_grasp_data.yaml

Improving structure and comments inside `config_robot/panda_grasp_data.yaml`.
This was requested in the tutorial PR https://github.com/ros-planning/moveit_tutorials/pull/302.
After merge this should be cherry-picked to kinetic.

Improve robot config description

---

README.md
config/moveit_grasps_config.yaml
config_robot/panda_grasp_data.yaml
launch/grasp_filter_demo.launch
launch/rviz.launch
src/grasp_filter.cpp

fixes some small issues in the grasp filter demo and improves the visualizations

improving grasp filter demo

---

config_robot/panda_grasp_data.yaml
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_data.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_scorer.h
src/grasp_candidate.cpp
src/grasp_data.cpp
src/grasp_generator.cpp
src/grasp_scorer.cpp

@henningkayser  @praveenramanujam
Adds suction voxel support and related documentation.

Grasp candidate

---

include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_scorer.h
src/grasp_generator.cpp
src/grasp_scorer.cpp

Fixing the suction voxel scoring by passing the result by ref

---

README.md

its tempting to think the README is the only available documentation

Remove duplicate documentation from tutorials

---

include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_generator.h
src/demo/grasp_filter_demo.cpp
src/demo/grasp_generator_demo.cpp
src/demo/grasp_pipeline_demo.cpp
src/grasp_generator.cpp

- Remove unused variables
- Fix incorrect comments
- Rename setIdealTCPGraspPose() and deprecate old name

Cleanup demos with better documentation

---

include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_generator.h
src/demo/grasp_filter_demo.cpp
src/demo/grasp_generator_demo.cpp
src/demo/grasp_pipeline_demo.cpp
src/grasp_generator.cpp

Minor fixup to #55 that targets master instead of melodic-devel

Rename set ideal pose

---

include/moveit_grasps/state_validity_callback.h

Validity callback should use joint limits

check that a joint state is in bounds in setFromIK

---

README.md
config/moveit_grasps_config.yaml
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_planner.h
launch/gdb_settings.gdb
launch/grasp_pipeline_demo.launch
launch/rviz/grasps.rviz
src/demo/grasp_filter_demo.cpp
src/demo/grasp_generator_demo.cpp
src/demo/grasp_pipeline_demo.cpp
src/grasp_generator.cpp
test/config/moveit_grasps_config.yaml
test/grasp_data_test.test
test/grasp_filter_test.test
test/grasp_generator_test.test

- For the demo, show all the debug tools
- Improve GDB support
- Commenting cleanup... remove reference to Baxter

Cleanup of demo and various commenting

---

src/grasp_planner.cpp

use new cartesian interpolator api

---

src/grasp_generator.cpp

Use new api for getIdealTCPGraspPose

---

include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_data.h
include/moveit_grasps/grasp_filter.h
include/moveit_grasps/grasp_generator.h
include/moveit_grasps/grasp_planner.h
src/demo/grasp_filter_demo.cpp
src/demo/grasp_generator_demo.cpp
src/demo/grasp_pipeline_demo.cpp
src/grasp_data.cpp
src/grasp_filter.cpp
src/grasp_generator.cpp

Includes #66. New changes in most recent commit
Replacement for #64

Std make shared

---

.travis.yml

This is a test of my code coverage PR to moveit_ci.  Once that is merged I can update this to use it.

code coverage reporting

---

config/moveit_grasps_config.yaml
config_robot/panda_grasp_data.yaml
include/moveit_grasps/grasp_candidate.h
include/moveit_grasps/grasp_filter.h
include/moveit_grasps/state_validity_callback.h
include/moveit_grasps/suction_grasp_candidate.h
include/moveit_grasps/suction_grasp_filter.h
include/moveit_grasps/suction_grasp_generator.h
include/moveit_grasps/suction_voxel_matrix.h
include/moveit_grasps/two_finger_grasp_filter.h
src/demo/grasp_pipeline_demo.cpp
src/demo/suction_grasp_pipeline_demo.cpp
src/grasp_candidate.cpp
src/grasp_filter.cpp
src/grasp_planner.cpp
src/suction_grasp_candidate.cpp
src/suction_grasp_data.cpp
src/suction_grasp_filter.cpp
src/suction_grasp_generator.cpp
src/two_finger_grasp_filter.cpp
src/two_finger_grasp_generator.cpp
test/suction_grasp_pipeline_test.cpp
test/two_finger_grasp_filter_test.cpp
test/two_finger_grasp_generator_test.cpp

This adds suction voxel collision objects at the active suction voxels so that the active regions aren't in contact with other objects in the planning scene

Filter out suction cup collisions
